# Problema do Artesao

O artesao precisa maximizar seu lucro

In [ ]:
#Importar
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#Importar biblioteca
import pandas as pd
from scipy.optimize import linprog
import numpy as np

##Especificações
 
O artesão gostaria de vender jarros e tigelas feira ou em uma loja. Ele consegue vender por 20 reais os jarros e 30 reais as tigelas na loja, já na feira ele deve vender em conjunto por 45 reais, ou seja, 22.50 reais por produto.
A loja compra até 30 jarros e pelo menos 8 tigelas. Além do mais, ela compra pelo menos o dobro de tigelas em relação aos jarros.
A sua produção máxima se resume em:
- Fazer somente tigelas ele faz 40
- Fazer somente jarros ele faz 50
 
O problema foi modelado da seguinte forma:


### Variaveis De Decisao
- x1 -> Producao de Jarros
- x2 -> Producao de Tijelas
- x3 -> Venda de Jarros para loja
- x4 -> Venda de Tijelas para loja
- x5 -> Venda de Jarros na feira
- x6 -> Venda de Tijelas na feira

### Funcoes

Maximizacao:

$0x1 + 0x2 + 20x3 + 30x4 + 22.5x5 + 22.5x6 = z$
<br>
<br>
Producao Jarros:
<br>
$0.8x1 + x2 \leq 40$
<br>
Ou
<br>
Producao Tijelas
<br>
$x1 + 1.25x2 \leq 50$
<br>
<br>
Venda Loja1:
<br>
$2x3 \leq x4$
<br>
<br>
Venda Loja2:
<br>
$x3 \leq 30$
<br>
<br>
Venda Loja3:
<br>
$x4 \geq 8$
<br>
<br>
Venda Feira:
<br>
$x5 = x6$
<br>
<br>
Restricao Venda1:
<br>
$x2 \geq x4 + x6$
<br>
<br>
Restricao Venda2:
<br>
$x1 \geq x3 + x5$


### Explicação
 
Produção:
A produção diz que quando não faz nenhum vaso ele produz 40 tigelas, além disso quando produz 50 vasos não produz tigelas. Com essas duas equações é possível saber a proporção de produção. A proporção de um objeto é dada pelo número produzido dividido pelo seu máximo. Então substituindo a proporção em alguma das equações consegue-se o valor da outra variável. Ex:
 
$x1 \leq 40 -(40(x2/50))$
 
 
Venda Loja 1:
O número de tigelas vendida na loja eh pelo menos 2x maior que o de jarros
 
Venda Loja2:
O número máximo de jarros vendidos na loja eh 30
 
Venda Loja 3:
O número mínimo de tigelas vendidas para loja eh 8
 
Venda Feira:
O número de vendas de tigelas na feira deve ser o mesmo que o de jarros
 
Restrição Venda:
As produção dos produtos não deve ser superior a venda, p.ex:
<br>
A venda de tigelas não deve ser maior que a produção das mesmas


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/7 periodo/PO/Prova/Prova - Artesao.csv")
df

Unnamed: 0  p_Jarros  p_Tijelas  ...  v_JarrosFeira  v_TijelasFeira   b
0       Lucro       0.0       0.00  ...           22.5            22.5   z
1  Rest_Prod0       0.8       1.00  ...            0.0             0.0  40
2  Rest_Prod1       1.0       1.25  ...            0.0             0.0  50
3  Rest_Prod2      -1.0       0.00  ...            1.0             0.0   0
4  Rest_Prod3       0.0      -1.00  ...            0.0             1.0   0
5  Rest_Loja0       0.0       0.00  ...            0.0             0.0  30
6  Rest_Loja1       0.0       0.00  ...            0.0             0.0  -8
7  Rest_Loja2       0.0       0.00  ...            0.0             0.0   0
8  Rest_Feira       0.0       0.00  ...           -1.0             1.0   0

[9 rows x 8 columns]

In [ ]:
#Funcao de Minimizacao
z = df.iloc[0, 1:-1].to_numpy(dtype="float32")
z

array([ 0. ,  0. , 20. , 30. , 22.5, 22.5], dtype=float32)

In [ ]:
A_limsup = df.iloc[1:8, 1:-1].to_numpy(dtype="float32")
A_limsup 

array([[ 0.8 ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 1.  ,  1.25,  0.  ,  0.  ,  0.  ,  0.  ],
       [-1.  ,  0.  ,  1.  ,  0.  ,  1.  ,  0.  ],
       [ 0.  , -1.  ,  0.  ,  1.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , -1.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  2.  , -1.  ,  0.  ,  0.  ]], dtype=float32)

In [ ]:
A_equ = np.array([df.iloc[8, 1:-1]])
A_equ

array([[0.0, 0.0, 0, 0, -1.0, 1.0]], dtype=object)

In [ ]:
b_sup = df.iloc[1:8, -1].to_numpy(dtype="float32")
b_sup

array([40., 50.,  0.,  0., 30., -8.,  0.], dtype=float32)

In [ ]:
b_equ = np.array([df.iloc[8, -1]], dtype="float32")
b_equ

array([0.], dtype=float32)

In [ ]:
x1_lim = (0,None)
x2_lim = (0,None)
x3_lim = (0,None)
x4_lim = (0,None)
x5_lim = (0,None)
x6_lim = (0,None)
limites = np.array([x1_lim,x2_lim,x3_lim,x4_lim,x5_lim,x6_lim])

In [ ]:
#Aplicar Funcao 
res = linprog(-z, A_ub = A_limsup, b_ub = b_sup, bounds = limites,
              A_eq = A_equ, b_eq = b_equ, method = 'simplex')
res

     con: array([0.])
     fun: -1200.0
 message: 'Optimization terminated successfully.'
     nit: 8
   slack: array([ 0.,  0.,  0.,  0., 30., 32., 40.])
  status: 0
 success: True
       x: array([ 0., 40.,  0., 40.,  0.,  0.])